graph: 'hprc-v1.1-mc-grch38'
gbz: "/scratch/pawsey0933/cfolland/vg_snakemake/refs/hprc-v1.1-mc-grch38.gbz"
hapl: "/scratch/pawsey0933/cfolland/vg_snakemake/refs/hprc-v1.1-mc-grch38.hapl"
ref_paths_list: 'config/hprc-v1.1-mc-grch38.paths_list.txt'
seqn_prefix: "GRCh38#0#"
gt_min_var_len: 30
indel_realign_reads: True
sample_tsv: "/scratch/pawsey0933/cfolland/vg_snakemake/config/sample_info.tsv"
