---
cores: 24 # reduced
latency-wait: 60 #increase latency wait
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 2
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
max-jobs-per-second: 10                 #Maximal number of cluster/drmaa jobs per second, default is 10, fractions allowed.
max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
jobs: 500                              #Use at most N CPU cluster/cloud jobs in parallel.
cluster: "sbatch --account=pawsey0933 --partition={resources.partition} --error=/scratch/pawsey0933/cfolland/vg_snakemake/logs/%j.%x.err --output=/scratch/pawsey0933/cfolland/vg_snakemake/%j.%x.out --no-requeue --mem={resources.mem_mb} --time={resources.runtime_min} --mail-user=chiara.folland@perkins.org.au --export=ALL"
# For some reason time needs quotes to be read by snakemake
default-resources:
  - runtime_min=720
  - mem_mb=80000
  - partition=work
# Job resources
#set-resources:
  #- haplotypeCaller:mem_mb=40000
 
